basePath: /
definitions:
  v1.errResponse:
    properties:
      error:
        type: string
    type: object
  v1.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: API for auth microservice
  version: "1.0"
paths:
  /v1/login:
    post:
      consumes:
      - application/json
      description: login
      operationId: login-user
      parameters:
      - description: Enter email, password
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.errResponse'
      summary: Login
      tags:
      - auth
  /v1/logout:
    post:
      consumes:
      - application/json
      description: logout
      operationId: logout-user
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.errResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/v1.errResponse'
      security:
      - ApiKeyAuth: []
      summary: Logout
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
